### ISSUE TITLE
Date.js not properly loaded

### ISSUE THREAD

**Issue by imfede** [N00bySumairu/SmoothAnalogClock.widget#1]
For some reason the widget couldn't load the Date.js library you included. Nothing I tried could make it work so I decided to ditch the library and change line 73 of your index.coffe to:
`time = Date.now() % (1000 * 60 * 60 *24)`
and removing all the code related to the library loading.
After that it worked flawlessly :)
I'm opening this issue just to let you know that the external lib is not needed and it's only a cause for problems

**Comment by N00bySumairu** [comment]
Thanks for telling me this, at the time I really just wanted it to work quickly, the date.js library seemed like it might do the job, so I chose to use it. I will update the code, so it doesn't need the library anymore.

**Comment by imfede** [comment]
Quick tip. Use
`time = Date.now() - (new Date()).setHours(0,0,0,0)`
instead of what I wrote earlier.
Thanks for the quick response and keep up the good work 👍

**Comment by N00bySumairu** [comment]
Thanks for helping, I appreciate it.

**Comment by N00bySumairu** [comment]
The code is updated, thanks again for creating an issue and helping.
